# Generated by Django 3.0.6 on 2020-05-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todolist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todoitem',
            name='author_ip',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='todoitem',
            name='done_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
